version: "3"

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
      - /var/log:/var/log
      - /var/lib/systemd:/var/lib/systemd
      - /run/log/journal:/run/log/journal
      - /etc/machine-id:/etc/machine-id
      - ./positions.yaml:/tmp/positions.yaml  # ✅ Host-side file to persist positions

    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      loki:
        condition: service_healthy  # ✅ wait for Loki to be healthy before starting
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      loki:
        condition: service_healthy  # ✅ wait for Loki to be healthy
    restart: unless-stopped
    # 🔁 Removed Grafana healthcheck because it doesn't expose /ready by default
    # If needed, you can add a custom script or use the API

volumes:
  grafana-storage:
  loki-data:
